services:

  # REDIS
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6378:6379'
    environment:
      - REDIS_PASSWORD=my-password
    volumes:
      - redisdata:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 120

  #myapp:
  #  image: myapp-0.0.1:latest
  #  ports:
  #    - '8000:8000'
  #  networks:
  #    - backend

volumes:
  redisdata:

networks:
  backend: